- name: Install fish
  ansible.builtin.package:
    name: fish
    state: present

- name: Create directory the fish configuration directory if not exists
  ansible.builtin.file:
    path: $HOME/.config/fish
    state: directory
    mode: "0755"
  become: false

- name: Copy the fish configuration directory
  ansible.builtin.copy:
    src: ../../common/files/fish
    dest: $HOME/.config
    force: true
    mode: "0755"
  become: false

- name: Set fish as the default shell for the current user
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    shell: "{{ lookup('pipe', 'which fish') }}"

- name: Set fish as the default shell for every user
  ansible.builtin.lineinfile:
    path: /etc/default/useradd
    regexp: "SHELL="
    line: "SHELL=/usr/bin/fish"
