- name: Install fish
  ansible.builtin.package:
    name: fish
    state: present

- name: Check if the fish configuration directory exists
  ansible.builtin.stat:
    path: $HOME/.config/fish
  register: fish_home_dir

- name: Ansible create directory the fish configuration directory if not exists
  ansible.builtin.file:
    path: $HOME/.config/fish
    state: directory
    mode: 0755
    recurse: yes
  when: fish_home_dir.stat.exists == false

- name: Copy the fish configuration directory
  ansible.builtin.copy:
    src: ../../common/files/fish
    dest: $HOME/.config
    force: yes

# - name: Download oh-my-fish install script
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
#     dest: /tmp/install

# - name: Install oh-my-fish
#   ansible.builtin.shell: fish /tmp/install --yes --noninteractive
#   become_method: su

# - name: Install oh-my-fish plugins
#   ansible.builtin.shell: fish -c "omf install {{ item }}"
#   loop:
#     - bobthefish
#     - peco
#     - bang-bang
#     - foreign-env

- name: Set fish as the default shell for the current user
  ansible.builtin.shell: |
    usermod --shell $(which fish) {{ ansible_ssh_user }}

- name: Set fish as the default shell for every user
  lineinfile:
    path: /etc/default/useradd
    regexp: "SHELL="
    line: "SHELL=/usr/bin/fish"
