# Taken from https://github.com/hashbang/shell-server/blob/797cec330b69fcc022581593aba42c0cd4641133/ansible/tasks/profile/main.yml#L97
- name: Remove default /etc/skel directory
  ansible.builtin.file:
    path: "/etc/skel/{{ item }}"
    state: absent
  loop:
    - .bash_logout
    - .bashrc
    - .kshrc
    - .mkshrc

- name: Override the useradd command configuration
  ansible.builtin.replace:
    path: /etc/default/useradd
    regexp: "# SKEL"
    replace: "SKEL"

- name: Create the config directory if not exists
  ansible.builtin.file:
    path: /etc/skel/.config
    state: directory
    mode: "0755"
    recurse: true

- name: Copy the fish configuration directory
  ansible.builtin.copy:
    src: ../../common/files/fish
    dest: /etc/skel/.config
    mode: "0755"
    force: true

- name: Copy the tmux configuration file
  ansible.builtin.copy:
    src: ../../common/files/.tmux.conf
    dest: /etc/skel/
    mode: "0644"
    force: true
