- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Copy the fail2ban configuration file
  ansible.builtin.copy:
    src: fail2ban/jail.local
    dest: /etc/fail2ban
    mode: "0644"

- name: Restart service fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true
