- name: Override the SSH daemon configuration
  ansible.builtin.shell: |
    sed -i \
      -e 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' \
      -e 's/#Port 22/Port {{ ssh_port }}/' \
      -e 's/#SyslogFacility/SyslogFacility/' \
      -e 's/#LogLevel/LogLevel/' \
      -e 's/#PubkeyAuthentication/PubkeyAuthentication/' \
      /etc/ssh/sshd_config
  become: yes

- name: Restart service ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: yes
