- name: Override the SSH daemon configuration
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: "#PermitRootLogin prohibit-password", replace: "PermitRootLogin yes" }
    - { regexp: "#Port 22", replace: "Port {{ ssh_port }}" }
    - { regexp: "#SyslogFacility", replace: "SyslogFacility" }
    - { regexp: "#LogLevel", replace: "LogLevel" }
    - { regexp: "#PubkeyAuthentication", replace: "PubkeyAuthentication" }

- name: Restart service ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
