- name: Install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - sed
    - apache2-utils
    - sudo
    - exa
    - nginx
    - libnginx-mod-stream
