- name: Update debian packages with apt
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade debian packages with apt
  ansible.builtin.apt:
    upgrade: safe

- name: Install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - sed
    - apache2-utils
    - sudo
    - exa
    - cron
    - gzip
    - make
